[package]
name = "osom-llm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
osom-config = { path = "../osom-config" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
tokio = { workspace = true }
tracing = { workspace = true }
async-trait = "0.1"
