[package]
name = "osom-writer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
osom-config = { path = "../osom-config" }
osom-schema = { path = "../osom-schema" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
quick-xml = { version = "0.36", features = ["serialize"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "postgres", "mysql", "migrate"] }
tokio = { workspace = true }
tracing = { workspace = true }
